### ISSUE TITLE
Plugin errors

### ISSUE THREAD

**Issue by hungnguyennaz** [TinLite/NoAdsInChat#2]
Could not pass events when joining, chatting.
![image](https://user-images.githubusercontent.com/101444336/171526156-284cb9ac-7bf7-4a66-a338-289fd10fb8fe.png)
![image](https://user-images.githubusercontent.com/101444336/171526195-e2c0192a-8383-4d22-8d3f-cf90cebc1b7b.png)
[Pastes](https://pastes.dev/ok4d3uTStN)
Using [Pearl](https://github.com/Pearl-Project/Pearl) 1.18.2, Windows.

**Comment by TinLite** [comment]
Hello. Sorry for the late reply.

Can you check if there is an error on plugin startup?

**Comment by TinLite** [comment]
Oof sorry I didn't aware that kind of commit message will close this issue.

I'm able to reproduce this bug as well. Please try this version: https://github.com/TinLite/NoAdsInChat/suites/6759546212/artifacts/258424701

**Comment by hungnguyennaz** [comment]
I don't see any

> Hello. Sorry for the late reply.
> 
> Can you check if there is an error on plugin startup?

I don't see any errors on plugin startup 
![image](https://user-images.githubusercontent.com/101444336/171578288-c881afef-ce65-4386-a5df-75592f5228f1.png)

**Comment by hungnguyennaz** [comment]
I'm still getting errors on 1.2.4 😭 
![image](https://user-images.githubusercontent.com/101444336/171578415-c6b7d946-6ff6-4c7e-ba6a-ce0b150b38b5.png)

**Comment by TinLite** [comment]
Hello, please try this version

[NoAdsInChat-1.2.4 patch.zip](https://github.com/TinLite/NoAdsInChat/files/8822172/NoAdsInChat-1.2.4.patch.zip)
